### ISSUE TITLE
TypeScript complains that area doesn't exists

### ISSUE THREAD

**Issue by Hagendorn** [nbubna/store#100] opened 2022-03-11 14:30 UTC
I updated our project from `2.12.0` to `2.13.1` and now TypeScript says that `area` does not exist anymore:

![Screen Shot 2022-03-11 at 15 25 40](https://user-images.githubusercontent.com/200940/157886767-3f9c6787-815a-4603-96f7-943dc9473aeb.png)

Looks to me that this commit broke the types:
https://github.com/nbubna/store/commit/1ca5d1605bfdd8f1662317e8f7182f91d5075439

**Comment by nbubna** [comment] 2022-03-14 16:39
Eek! Sorry, total oversight there. Bugfix version coming shortly.

**Comment by nbubna** [comment] 2022-03-14 16:50
2.13.2 is out w/fix for this.

**Closed by nbubna** 2022-03-14 16:50 UTC

**Comment by mohitgarg** [comment] 2023-02-14 12:23
Hi @nbubna, I think it's still broke on 2.14.2. I am getting the same error `TS2339: Property 'get' does not exist on type 'typeof import("/......../node_modules/store2/index")'.`

**Comment by nbubna** [comment] 2023-02-14 16:57
But that's not the same error...

**Comment by mohitgarg** [comment] 2023-02-14 17:28
Same typescript error I mean. `property X doesn't exist on type Y`

**Comment by nbubna** [comment] 2023-02-14 17:42
This is not an issue for any or all TypeScript complaints. This issue was and still is fixed. Please open a new issue, and provide steps for replication. Because i use store.get all the time in TypeScript without errors. And if you look at the index.d.ts, you can clearly see that StoreType includes StoreBase, which includes StoreAPI, which defines 'get'.

**Comment by mohitgarg** [comment] 2023-02-14 18:16
Let me check my `tsconfig` and try to reproduce it. I'll get back to you. Thank you for replying back. Appreciate the work.
